export default [
  { "code": "ALL", "name": "Albania Lek", "symbol": "&#76;&#101;&#107;" },
  { "code": "AFN", "name": "Afghanistan Afghani", "symbol": "&#1547;" },
  { "code": "ARS", "name": "Argentina Peso", "symbol": "&#36;" },
  { "code": "AWG", "name": "Aruba Guilder", "symbol": "&#402;" },
  { "code": "AUD", "name": "Australia Dollar", "symbol": "&#36;" },
  { "code": "AZN", "name": "Azerbaijan New Manat", "symbol": "&#1084;&#1072;&#1085;" },
  { "code": "BSD", "name": "Bahamas Dollar", "symbol": "&#36;" },
  { "code": "BBD", "name": "Barbados Dollar", "symbol": "&#36;" },
  { "code": "BYR", "name": "Belarus Ruble", "symbol": "&#112;&#46;" },
  { "code": "BZD", "name": "Belize Dollar", "symbol": "&#66;&#90;&#36;" },
  { "code": "BMD", "name": "Bermuda Dollar", "symbol": "&#36;" },
  { "code": "BOB", "name": "Bolivia Boliviano", "symbol": "&#36;&#98;" },
  { "code": "BAM", "name": "Bosnia and Herzegovina Convertible Marka", "symbol": "&#75;&#77;" },
  { "code": "BWP", "name": "Botswana Pula", "symbol": "&#80;" },
  { "code": "BGN", "name": "Bulgaria Lev", "symbol": "&#1083;&#1074;" },
  { "code": "BRL", "name": "Brazil Real", "symbol": "&#82;&#36;" },
  { "code": "BND", "name": "Brunei Darussalam Dollar", "symbol": "&#36;" },
  { "code": "KHR", "name": "Cambodia Riel", "symbol": "&#6107;" },
  { "code": "CAD", "name": "Canada Dollar", "symbol": "&#36;" },
  { "code": "KYD", "name": "Cayman Islands Dollar", "symbol": "&#36;" },
  { "code": "CLP", "name": "Chile Peso", "symbol": "&#36;" },
  { "code": "CNY", "name": "China Yuan Renminbi", "symbol": "&#165;" },
  { "code": "COP", "name": "Colombia Peso", "symbol": "&#36;" },
  { "code": "CRC", "name": "Costa Rica Colon", "symbol": "&#8353;" },
  { "code": "HRK", "name": "Croatia Kuna", "symbol": "&#107;&#110;" },
  { "code": "CUP", "name": "Cuba Peso", "symbol": "&#8369;" },
  { "code": "CZK", "name": "Czech Republic Koruna", "symbol": "&#75;&#269;" },
  { "code": "DKK", "name": "Denmark Krone", "symbol": "&#107;&#114;" },
  { "code": "DOP", "name": "Dominican Republic Peso", "symbol": "&#82;&#68;&#36;" },
  { "code": "XCD", "name": "East Caribbean Dollar", "symbol": "&#36;" },
  { "code": "EGP", "name": "Egypt Pound", "symbol": "&#163;" },
  { "code": "SVC", "name": "El Salvador Colon", "symbol": "&#36;" },
  { "code": "EEK", "name": "Estonia Kroon", "symbol": "&#107;&#114;" },
  { "code": "EUR", "name": "Euro Member Countries", "symbol": "&#8364;" },
  { "code": "FKP", "name": "Falkland Islands (Malvinas) Pound", "symbol": "&#163;" },
  { "code": "FJD", "name": "Fiji Dollar", "symbol": "&#36;" },
  { "code": "GHC", "name": "Ghana Cedis", "symbol": "&#162;" },
  { "code": "GIP", "name": "Gibraltar Pound", "symbol": "&#163;" },
  { "code": "GTQ", "name": "Guatemala Quetzal", "symbol": "&#81;" },
  { "code": "GGP", "name": "Guernsey Pound", "symbol": "&#163;" },
  { "code": "GYD", "name": "Guyana Dollar", "symbol": "&#36;" },
  { "code": "HNL", "name": "Honduras Lempira", "symbol": "&#76;" },
  { "code": "HKD", "name": "Hong Kong Dollar", "symbol": "&#36;" },
  { "code": "HUF", "name": "Hungary Forint", "symbol": "&#70;&#116;" },
  { "code": "ISK", "name": "Iceland Krona", "symbol": "&#107;&#114;" },
  { "code": "INR", "name": "India Rupee", "symbol": null },
  { "code": "IDR", "name": "Indonesia Rupiah", "symbol": "&#82;&#112;" },
  { "code": "IRR", "name": "Iran Rial", "symbol": "&#65020;" },
  { "code": "IMP", "name": "Isle of Man Pound", "symbol": "&#163;" },
  { "code": "ILS", "name": "Israel Shekel", "symbol": "&#8362;" },
  { "code": "JMD", "name": "Jamaica Dollar", "symbol": "&#74;&#36;" },
  { "code": "JPY", "name": "Japan Yen", "symbol": "&#165;" },
  { "code": "JEP", "name": "Jersey Pound", "symbol": "&#163;" },
  { "code": "KZT", "name": "Kazakhstan Tenge", "symbol": "&#1083;&#1074;" },
  { "code": "KPW", "name": "Korea (North) Won", "symbol": "&#8361;" },
  { "code": "KRW", "name": "Korea (South) Won", "symbol": "&#8361;" },
  { "code": "KGS", "name": "Kyrgyzstan Som", "symbol": "&#1083;&#1074;" },
  { "code": "LAK", "name": "Laos Kip", "symbol": "&#8365;" },
  { "code": "LVL", "name": "Latvia Lat", "symbol": "&#76;&#115;" },
  { "code": "LBP", "name": "Lebanon Pound", "symbol": "&#163;" },
  { "code": "LRD", "name": "Liberia Dollar", "symbol": "&#36;" },
  { "code": "LTL", "name": "Lithuania Litas", "symbol": "&#76;&#116;" },
  { "code": "MKD", "name": "Macedonia Denar", "symbol": "&#1076;&#1077;&#1085;" },
  { "code": "MWK", "name": "Malawian Kwacha", "symbol": "MK" },
  { "code": "MYR", "name": "Malaysia Ringgit", "symbol": "&#82;&#77;" },
  { "code": "MUR", "name": "Mauritius Rupee", "symbol": "&#8360;" },
  { "code": "MXN", "name": "Mexico Peso", "symbol": "&#36;" },
  { "code": "MNT", "name": "Mongolia Tughrik", "symbol": "&#8366;" },
  { "code": "MZN", "name": "Mozambique Metical", "symbol": "&#77;&#84;" },
  { "code": "NAD", "name": "Namibia Dollar", "symbol": "&#36;" },
  { "code": "NPR", "name": "Nepal Rupee", "symbol": "&#8360;" },
  { "code": "ANG", "name": "Netherlands Antilles Guilder", "symbol": "&#402;" },
  { "code": "NZD", "name": "New Zealand Dollar", "symbol": "&#36;" },
  { "code": "NIO", "name": "Nicaragua Cordoba", "symbol": "&#67;&#36;" },
  { "code": "NGN", "name": "Nigeria Naira", "symbol": "&#8358;" },
  { "code": "KPW", "name": "Korea (North) Won", "symbol": "&#8361;" },
  { "code": "NOK", "name": "Norway Krone", "symbol": "&#107;&#114;" },
  { "code": "OMR", "name": "Oman Rial", "symbol": "&#65020;" },
  { "code": "PKR", "name": "Pakistan Rupee", "symbol": "&#8360;" },
  { "code": "PAB", "name": "Panama Balboa", "symbol": "&#66;&#47;&#46;" },
  { "code": "PYG", "name": "Paraguay Guarani", "symbol": "&#71;&#115;" },
  { "code": "PEN", "name": "Peru Nuevo Sol", "symbol": "&#83;&#47;&#46;" },
  { "code": "PHP", "name": "Philippines Peso", "symbol": "&#8369;" },
  { "code": "PLN", "name": "Poland Zloty", "symbol": "&#122;&#322;" },
  { "code": "QAR", "name": "Qatar Riyal", "symbol": "&#65020;" },
  { "code": "RON", "name": "Romania New Leu", "symbol": "&#108;&#101;&#105;" },
  { "code": "RUB", "name": "Russia Ruble", "symbol": "&#1088;&#1091;&#1073;" },
  { "code": "SHP", "name": "Saint Helena Pound", "symbol": "&#163;" },
  { "code": "SAR", "name": "Saudi Arabia Riyal", "symbol": "&#65020;" },
  { "code": "RSD", "name": "Serbia Dinar", "symbol": "&#1044;&#1080;&#1085;&#46;" },
  { "code": "SCR", "name": "Seychelles Rupee", "symbol": "&#8360;" },
  { "code": "SGD", "name": "Singapore Dollar", "symbol": "&#36;" },
  { "code": "SBD", "name": "Solomon Islands Dollar", "symbol": "&#36;" },
  { "code": "SOS", "name": "Somalia Shilling", "symbol": "&#83;" },
  { "code": "ZAR", "name": "South Africa Rand", "symbol": "&#82;" },
  { "code": "KRW", "name": "Korea (South) Won", "symbol": "&#8361;" },
  { "code": "LKR", "name": "Sri Lanka Rupee", "symbol": "&#8360;" },
  { "code": "SEK", "name": "Sweden Krona", "symbol": "&#107;&#114;" },
  { "code": "CHF", "name": "Switzerland Franc", "symbol": "&#67;&#72;&#70;" },
  { "code": "SRD", "name": "Suriname Dollar", "symbol": "&#36;" },
  { "code": "SYP", "name": "Syria Pound", "symbol": "&#163;" },
  { "code": "TWD", "name": "Taiwan New Dollar", "symbol": "&#78;&#84;&#36;" },
  { "code": "THB", "name": "Thailand Baht", "symbol": "&#3647;" },
  { "code": "TTD", "name": "Trinidad and Tobago Dollar", "symbol": "&#84;&#84;&#36;" },
  { "code": "TRY", "name": "Turkey Lira", "symbol": "tl" },
  { "code": "TRL", "name": "Turkey Lira", "symbol": "&#8356;" },
  { "code": "TVD", "name": "Tuvalu Dollar", "symbol": "&#36;" },
  { "code": "UAH", "name": "Ukraine Hryvna", "symbol": "&#8372;" },
  { "code": "GBP", "name": "United Kingdom Pound", "symbol": "&#163;" },
  { "code": "USD", "name": "United States Dollar", "symbol": "&#36;" },
  { "code": "UYU", "name": "Uruguay Peso", "symbol": "&#36;&#85;" },
  { "code": "UZS", "name": "Uzbekistan Som", "symbol": "&#1083;&#1074;" },
  { "code": "VEF", "name": "Venezuela Bolivar", "symbol": "&#66;&#115;" },
  { "code": "VND", "name": "Viet Nam Dong", "symbol": "&#8363;" },
  { "code": "YER", "name": "Yemen Rial", "symbol": "&#65020;" },
  { "code": "ZMW", "name": "Zambian Kwacha", "symbol": "ZK" },
  { "code": "ZWD", "name": "Zimbabwe Dollar", "symbol": "&#90;&#36;" }
]
